DROP TABLE AUTHOR;
CREATE TABLE AUTHOR
  (
    ID_AUTHOR VARCHAR(255) NOT NULL ,
    NAME      VARCHAR(255),
    SURNAME VARCHAR(255),
    ALIAS VARCHAR(255),
    PRIMARY KEY ( ID_AUTHOR )
  ) ;

DROP TABLE CATEGORY;
CREATE TABLE CATEGORY
  (
    ID_CATEGORY VARCHAR(255) NOT NULL ,
    NAME        VARCHAR(255),
    PRIMARY KEY ( ID_CATEGORY )
  ) ;

DROP TABLE CHANNEL;
CREATE TABLE CHANNEL
  (
    ID_CHANNEL VARCHAR(255) NOT NULL ,
    TYPE       VARCHAR(255),
    PRIMARY KEY ( ID_CHANNEL )
  ) ;

DROP TABLE CLIENTS;
CREATE TABLE CLIENTS
  (
    ID_CLIENTS VARCHAR(255) NOT NULL ,
    NAME       VARCHAR(255),
    SURNAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255),
    PRIMARY KEY ( ID_CLIENTS )
  ) ;

DROP TABLE DATA;
CREATE TABLE DATA
  (
    ID_DATA            VARCHAR(255) NOT NULL ,
    DAY                INT ,
    ID_DAY_OF_THE_WEEK INT NOT NULL ,
    ID_QUARTER         INT NOT NULL ,
    ID_MONTH           INT NOT NULL ,
    ID_YEAR            VARCHAR(255) NOT NULL,
    PRIMARY KEY ( ID_DATA )
  ) ;

DROP TABLE DAY_OF_WEEK;
CREATE TABLE DAY_OF_WEEK
  (
    ID_DAY_OF_THE_WEEK INT NOT NULL ,
    NAME               VARCHAR(255),
    PRIMARY KEY ( ID_DAY_OF_THE_WEEK )
  ) ;

DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES
  (
    ID_EMPLOYEES VARCHAR(255) NOT NULL ,
    NAME         VARCHAR(255),
    SURNAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    EMAIL VARCHAR(255),
    "DATE_OF_EMPLOYMENT" DATE ,
    SALARY                NUMERIC(10,2),
    PRIMARY KEY ( ID_EMPLOYEES )
  ) ;

DROP TABLE INVOICE;
CREATE TABLE INVOICE
  (
    ID_INVOICE   VARCHAR(255) NOT NULL ,
    RESULT_PRICE NUMERIC(10,2) ,
    TAX_VALUE    NUMERIC(10,2) ,
    DISCOUNT     NUMERIC(10,2),
    PRIMARY KEY ( ID_INVOICE )
  ) ;

DROP TABLE MONTH;
CREATE TABLE MONTH
  (
    ID_MONTH INT NOT NULL ,
    MONTH    VARCHAR(255),
    PRIMARY KEY ( ID_MONTH )
  ) ;

DROP TABLE PAYMENT;
CREATE TABLE PAYMENT
  (
    ID_PAYMENT VARCHAR(255) NOT NULL ,
    TYPE       VARCHAR(255),
    PRIMARY KEY ( ID_PAYMENT )
  ) ;

DROP TABLE PRODUCER;
CREATE TABLE PRODUCER
  (
    ID_PRODUCER VARCHAR(255) NOT NULL ,
    NAME        VARCHAR(255),
    ADDRESS VARCHAR(255),
    PRIMARY KEY ( ID_PRODUCER )
  ) ;

DROP TABLE PRODUCT;
CREATE TABLE PRODUCT
  (
    ID_PRODUCT  VARCHAR(255) NOT NULL ,
    ID_CATEGORY VARCHAR(255) NOT NULL ,
    ID_PRODUCER VARCHAR(255) NOT NULL ,
    ID_AUTHOR   VARCHAR(255) NOT NULL ,
    NAME        VARCHAR(255) NOT NULL,
    PRICE       NUMERIC(10,2),
    PRIMARY KEY ( ID_PRODUCT )
  ) ;

DROP TABLE QUARTER;
CREATE TABLE QUARTER
  ( ID_QUARTER INT NOT NULL ,
    NUM_OF_Q INT,
    PRIMARY KEY ( ID_QUARTER )
  ) ;

DROP TABLE SALES;
CREATE TABLE SALES
  (
    ID_SALES     VARCHAR(255) NOT NULL ,
    ID_CLIENTS   VARCHAR(255) NOT NULL ,
    ID_EMPLOYEES VARCHAR(255) NOT NULL ,
    ID_DATA      VARCHAR(255) NOT NULL ,
    ID_PRODUCT   VARCHAR(255) NOT NULL ,
    ID_PAYMENT   VARCHAR(255) NOT NULL ,
    ID_CHANNEL   VARCHAR(255) NOT NULL ,
    QUANTITY     INT ,
    ID_INVOICE   VARCHAR(255) NOT NULL
  ) ;

DROP TABLE YEAR;
CREATE TABLE YEAR
  ( ID_YEAR VARCHAR(255) NOT NULL , YEAR INT
  ) ;
ALTER TABLE YEAR ADD CONSTRAINT YEAR_PK PRIMARY KEY ( ID_YEAR ) ;


ALTER TABLE DATA ADD CONSTRAINT DATA_DAY_OF_WEEK_FK FOREIGN KEY ( ID_DAY_OF_THE_WEEK ) REFERENCES DAY_OF_WEEK ( ID_DAY_OF_THE_WEEK ) ;

ALTER TABLE DATA ADD CONSTRAINT DATA_MONTH_FK FOREIGN KEY ( ID_MONTH ) REFERENCES MONTH ( ID_MONTH ) ;

ALTER TABLE DATA ADD CONSTRAINT DATA_QUARTER_FK FOREIGN KEY ( ID_QUARTER ) REFERENCES QUARTER ( ID_QUARTER ) ;

ALTER TABLE DATA ADD CONSTRAINT DATA_YEAR_FK FOREIGN KEY ( ID_YEAR ) REFERENCES YEAR ( ID_YEAR ) ;

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_AUTHOR_FK FOREIGN KEY ( ID_AUTHOR ) REFERENCES AUTHOR ( ID_AUTHOR ) ;

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_CATEGORY_FK FOREIGN KEY ( ID_CATEGORY ) REFERENCES CATEGORY ( ID_CATEGORY ) ;

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PRODUCER_FK FOREIGN KEY ( ID_PRODUCER ) REFERENCES PRODUCER ( ID_PRODUCER ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_CHANNEL_FK FOREIGN KEY ( ID_CHANNEL ) REFERENCES CHANNEL ( ID_CHANNEL ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_CLIENTS_FK FOREIGN KEY ( ID_CLIENTS ) REFERENCES CLIENTS ( ID_CLIENTS ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_DATA_FK FOREIGN KEY ( ID_DATA ) REFERENCES DATA ( ID_DATA ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_EMPLOYEES_FK FOREIGN KEY ( ID_EMPLOYEES ) REFERENCES EMPLOYEES ( ID_EMPLOYEES ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_INVOICE_FK FOREIGN KEY ( ID_INVOICE ) REFERENCES INVOICE ( ID_INVOICE ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_PAYMENT_FK FOREIGN KEY ( ID_PAYMENT ) REFERENCES PAYMENT ( ID_PAYMENT ) ;

ALTER TABLE SALES ADD CONSTRAINT SALES_PRODUCT_FK FOREIGN KEY ( ID_PRODUCT ) REFERENCES PRODUCT ( ID_PRODUCT ) ;