-- ****************** SqlDBM: Microsoft SQL Server ******************
-- ******************************************************************

DROP TABLE [TRAVEL_SALE];
GO


DROP TABLE [DAY];
GO


DROP TABLE [EMPLOYEE];
GO


DROP TABLE [TRAVEL];
GO


DROP TABLE [MONTH];
GO


DROP TABLE [BRANCH];
GO


DROP TABLE [CUSTOMER];
GO


DROP TABLE [STARTING_PLACE];
GO


DROP TABLE [TRAVEL_DESTINATION];
GO


DROP TABLE [TRAVEL_TYPE];
GO


DROP TABLE [BOUGHT_CHANNEL];
GO


DROP TABLE [PAYMENT_METHOD];
GO


DROP TABLE [YEAR];
GO


DROP TABLE [BRANCH_ADDRESS];
GO


DROP TABLE [CUSTOMER_ADDRESS];
GO


-- ************************************** [STARTING_PLACE]

CREATE TABLE [STARTING_PLACE]
(
 [STARTING_PLACE_ID] VARCHAR(255) NOT NULL ,
 [CITY]         VARCHAR(255) NOT NULL ,
 [STREET]           VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_STARTING_PLACE] PRIMARY KEY CLUSTERED ([STARTING_PLACE_ID] ASC)
);
GO





-- ************************************** [TRAVEL_DESTINATION]

CREATE TABLE [TRAVEL_DESTINATION]
(
 [TRAVEL_DESTINATION_ID] VARCHAR(255) NOT NULL ,
 [CONTINENT]             VARCHAR(255) NOT NULL ,
 [COUNTRY]               VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_TRAVEL_DESTINATION] PRIMARY KEY CLUSTERED ([TRAVEL_DESTINATION_ID] ASC)
);
GO





-- ************************************** [TRAVEL_TYPE]

CREATE TABLE [TRAVEL_TYPE]
(
 [TRAVEL_TYPE_ID] VARCHAR(255) NOT NULL ,
 [TYPE]           VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_TRAVEL_TYPE] PRIMARY KEY CLUSTERED ([TRAVEL_TYPE_ID] ASC)
);
GO





-- ************************************** [BOUGHT_CHANNEL]

CREATE TABLE [BOUGHT_CHANNEL]
(
 [BOUGHT_CHANNEL_ID] VARCHAR(255) NOT NULL ,
 [BOUGHT_CHANNEL]    VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_BOUGHT_CHANNEL] PRIMARY KEY CLUSTERED ([BOUGHT_CHANNEL_ID] ASC)
);
GO





-- ************************************** [PAYMENT_METHOD]

CREATE TABLE [PAYMENT_METHOD]
(
 [PAYMENT_METHOD_ID] VARCHAR(255) NOT NULL ,
 [PAYMENT_METHOD]    VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_PAYMENT_METHOD] PRIMARY KEY CLUSTERED ([PAYMENT_METHOD_ID] ASC)
);
GO





-- ************************************** [YEAR]

CREATE TABLE [YEAR]
(
 [YEAR_ID] VARCHAR(255) NOT NULL ,
 [YEAR]    INT NOT NULL ,

 CONSTRAINT [PK_YEAR] PRIMARY KEY CLUSTERED ([YEAR_ID] ASC)
);
GO





-- ************************************** [BRANCH_ADDRESS]

CREATE TABLE [BRANCH_ADDRESS]
(
 [BRANCH_ADDRESS_ID] VARCHAR(255) NOT NULL ,
 [COUNTRY]           VARCHAR(255) NOT NULL ,
 [CITY]              VARCHAR(255) NOT NULL ,
 [STREET]            VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_BRANCH_ADDRESS] PRIMARY KEY CLUSTERED ([BRANCH_ADDRESS_ID] ASC)
);
GO





-- ************************************** [CUSTOMER_ADDRESS]

CREATE TABLE [CUSTOMER_ADDRESS]
(
 [CUSTOMER_ADDRESS_ID] VARCHAR(255) NOT NULL ,
 [COUNTRY]             VARCHAR(255) NOT NULL ,
 [CITY]                VARCHAR(255) NOT NULL ,
 [STREET]              VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_CUSTOMER_ADDRESS] PRIMARY KEY CLUSTERED ([CUSTOMER_ADDRESS_ID] ASC)
);
GO





-- ************************************** [TRAVEL]

CREATE TABLE [TRAVEL]
(
 [TRAVEL_ID]             VARCHAR(255) NOT NULL ,
 [NUMBER_OF_PERSONS]     INT NOT NULL ,
 [PRICE]                 NUMERIC(10,2) NOT NULL ,
 [START_DATE]            DATETIME NOT NULL ,
 [END_DATE]              DATETIME NOT NULL ,
 [TRAVEL_DESTINATION_ID] VARCHAR(255) NOT NULL ,
 [STARTING_PLACE_ID]     VARCHAR(255) NOT NULL ,
 [TRAVEL_TYPE_ID]        VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_TRAVEL] PRIMARY KEY CLUSTERED ([TRAVEL_ID] ASC),
 CONSTRAINT [FK_89] FOREIGN KEY ([TRAVEL_DESTINATION_ID])
  REFERENCES [TRAVEL_DESTINATION]([TRAVEL_DESTINATION_ID]),
 CONSTRAINT [FK_92] FOREIGN KEY ([STARTING_PLACE_ID])
  REFERENCES [STARTING_PLACE]([STARTING_PLACE_ID]),
 CONSTRAINT [FK_95] FOREIGN KEY ([TRAVEL_TYPE_ID])
  REFERENCES [TRAVEL_TYPE]([TRAVEL_TYPE_ID])
);
GO


--SKIP Index: [fkIdx_89]

--SKIP Index: [fkIdx_92]

--SKIP Index: [fkIdx_95]




-- ************************************** [MONTH]

CREATE TABLE [MONTH]
(
 [MONTH_ID] VARCHAR(255) NOT NULL ,
 [MONTH]    INT NOT NULL ,
 [YEAR_ID]  VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_MONTH] PRIMARY KEY CLUSTERED ([MONTH_ID] ASC),
 CONSTRAINT [FK_54] FOREIGN KEY ([YEAR_ID])
  REFERENCES [YEAR]([YEAR_ID])
);
GO


--SKIP Index: [fkIdx_54]




-- ************************************** [BRANCH]

CREATE TABLE [BRANCH]
(
 [BRANCH_ID]         VARCHAR(255) NOT NULL ,
 [NAME]              VARCHAR(255) NOT NULL ,
 [BRANCH_ADDRESS_ID] VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_BRANCH] PRIMARY KEY CLUSTERED ([BRANCH_ID] ASC),
 CONSTRAINT [FK_36] FOREIGN KEY ([BRANCH_ADDRESS_ID])
  REFERENCES [BRANCH_ADDRESS]([BRANCH_ADDRESS_ID])
);
GO


--SKIP Index: [fkIdx_36]




-- ************************************** [CUSTOMER]

CREATE TABLE [CUSTOMER]
(
 [CUSTOMER_ID]         VARCHAR(255) NOT NULL ,
 [NAME]                VARCHAR(255) NOT NULL ,
 [SURNAME]             VARCHAR(255) NOT NULL ,
 [CUSTOMER_ADDRESS_ID] VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED ([CUSTOMER_ID] ASC),
 CONSTRAINT [FK_16] FOREIGN KEY ([CUSTOMER_ADDRESS_ID])
  REFERENCES [CUSTOMER_ADDRESS]([CUSTOMER_ADDRESS_ID])
);
GO


--SKIP Index: [fkIdx_16]




-- ************************************** [DAY]

CREATE TABLE [DAY]
(
 [DAY_ID]   VARCHAR(255) NOT NULL ,
 [DAY]      INT NOT NULL ,
 [MONTH_ID] VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_DAY] PRIMARY KEY CLUSTERED ([DAY_ID] ASC),
 CONSTRAINT [FK_57] FOREIGN KEY ([MONTH_ID])
  REFERENCES [MONTH]([MONTH_ID])
);
GO


--SKIP Index: [fkIdx_57]




-- ************************************** [EMPLOYEE]

CREATE TABLE [EMPLOYEE]
(
 [EMPLOYEE_ID] VARCHAR(255) NOT NULL ,
 [NAME]        VARCHAR(255) NOT NULL ,
 [SURNAME]     VARCHAR(255) NOT NULL ,
 [GENDER]      VARCHAR(1) NOT NULL ,
 [SALARY]      NUMERIC(10,2) NOT NULL ,
 [BRANCH_ID]   VARCHAR(255) NOT NULL ,

 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED ([EMPLOYEE_ID] ASC),
 CONSTRAINT [FK_39] FOREIGN KEY ([BRANCH_ID])
  REFERENCES [BRANCH]([BRANCH_ID])
);
GO


--SKIP Index: [fkIdx_39]




-- ************************************** [TRAVEL_SALE]

CREATE TABLE [TRAVEL_SALE]
(
 [TRAVEL_SALE_ID]      VARCHAR(255) NOT NULL ,
 [EMPLOYEE_ID]         VARCHAR(255) NOT NULL ,
 [CUSTOMER_ID] VARCHAR(255) NOT NULL ,
 [DAY_ID]              VARCHAR(255) NOT NULL ,
 [TRAVEL_ID]           VARCHAR(255) NOT NULL ,
 [BOUGHT_CHANNEL_ID]   VARCHAR(255) NOT NULL ,
 [PAYMENT_METHOD_ID]   VARCHAR(255) NOT NULL ,
 [TOTAL_PRICE]         NUMERIC(15,2) NOT NULL ,

 CONSTRAINT [PK_TRAVEL_SALE] PRIMARY KEY CLUSTERED ([TRAVEL_SALE_ID] ASC),
 CONSTRAINT [FK_101] FOREIGN KEY ([EMPLOYEE_ID])
  REFERENCES [EMPLOYEE]([EMPLOYEE_ID]),
 CONSTRAINT [FK_104] FOREIGN KEY ([CUSTOMER_ID])
  REFERENCES [CUSTOMER]([CUSTOMER_ID]),
 CONSTRAINT [FK_107] FOREIGN KEY ([DAY_ID])
  REFERENCES [DAY]([DAY_ID]),
 CONSTRAINT [FK_110] FOREIGN KEY ([TRAVEL_ID])
  REFERENCES [TRAVEL]([TRAVEL_ID]),
 CONSTRAINT [FK_113] FOREIGN KEY ([BOUGHT_CHANNEL_ID])
  REFERENCES [BOUGHT_CHANNEL]([BOUGHT_CHANNEL_ID]),
 CONSTRAINT [FK_116] FOREIGN KEY ([PAYMENT_METHOD_ID])
  REFERENCES [PAYMENT_METHOD]([PAYMENT_METHOD_ID])
);
GO


--SKIP Index: [fkIdx_101]

--SKIP Index: [fkIdx_104]

--SKIP Index: [fkIdx_107]

--SKIP Index: [fkIdx_110]

--SKIP Index: [fkIdx_113]

--SKIP Index: [fkIdx_116]




